name: github pages

on:
  push

jobs:
  gen-hugo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build HTML
        run: |
          hugo --minify --theme book
          tar czf page.tar.gz public

      - name: Upload page
        uses: actions/upload-artifact@v2
        with:
          name: page
          path: page.tar.gz
          retention-days: 2

  convert_via_pandoc:
    needs: [ gen-hugo ]
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.10
      options: --entrypoint=/bin/bash # does this work to force bash?
    steps:
      - uses: actions/checkout@v2

      - name: Install xmllint
        run: |
          apk add libxml2-utils

      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Prepare page tree
        run: |
          tar xf page/page.tar.gz

      - name: Build PDFs
        run: |
          set -eou pipefail
          export SHELLOPTS
          mkdir static
          find public/docs/mhb_* -type f -name "index.html" -print0 | \
            xargs -0 -n1 -I {} -P4 \
              sh -c "echo Converting \"{}\"...; xmllint --nowarning --html --xpath '/html/body/main/div/article' {} 2> /dev/null | \
                pandoc -f html -t pdf --template mhb_pandoc_template.latex -o \
                  static/\$(basename \$(dirname {})).pdf"
          mv static public/pdfs
          tar czf pageWithPdfs.tar.gz public

      - name: Upload page with PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pageWithPdfs
          path: pageWithPdfs.tar.gz
          retention-days: 2

  deploy-page:
    needs: [ gen-hugo, convert_via_pandoc ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Prepare page tree
        run: |
          tar xf pageWithPdfs/pageWithPdfs.tar.gz

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: endsWith(github.event.ref, '/master')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
