name: github pages

on:
  push

jobs:
  gen-hugo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build HTML
        run: |
          hugo --minify --theme book
          tar czf page.tar.gz public

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: version-1-4

      - name: Install musl
        shell: bash
        run: |
          sudo apt-get install musl-tools

      - name: Install parsetoml
        shell: bash
        run: |
          nimble refresh -y
          nimble install parsetoml -y

      - name: Build binary
        run: |
          cd tools
          nim musl genPdfs.nim
          cd ..
          tar czf tools.tar.gz tools

      - name: Upload page
        uses: actions/upload-artifact@v2
        with:
          name: page
          path: page.tar.gz
          retention-days: 2

      - name: Upload tools
        uses: actions/upload-artifact@v2
        with:
          name: tools
          path: tools.tar.gz
          retention-days: 2

  convert_via_pandoc:
    needs: [ gen-hugo ]
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.10
      options: --entrypoint=/bin/bash -l -c # does this work to force bash?
    steps:
      - uses: actions/checkout@v2

      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Prepare page tree
        run: |
          tar xf page/page.tar.gz

      - name: Unpack tools and run
        run: |
          tar xf tools/tools.tar.gz
          ls
          echo "----"
          cd tools
          ls
          chmod +x genPdfs
          ./genPdfs

      - name: Upload page with PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pageWithPdfs
          path: pageWithPdfs.tar.gz
          retention-days: 2

  deploy-page:
    needs: [ gen-hugo, convert_via_pandoc ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Prepare page tree
        run: |
          tar xf pageWithPdfs/pageWithPdfs.tar.gz

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: endsWith(github.event.ref, '/master')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
