name: github pages

on:
  push

jobs:
  gen-hugo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build HTML
        run: |
          hugo --minify --theme book
          tar czf page.tar.gz public

      - name: Upload page
        uses: actions/upload-artifact@v2
        with:
          name: page
          path: page.tar.gz
          retention-days: 2

  convert_via_pandoc:
    runs-on: ubuntu-20.04
    container:
      image: docker://pandoc/latex:2.10
      options: --entrypoint=sh
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build PDFs
        run: |
          mkdir static
          find public/docs/mhb_* -name "index.html" | while read fname; do
            echo $(dirname $fname).pdf
            xmllint --nowarning --html --xpath '/html/body/main/div/article' $fname 2> /dev/null | \
              pandoc -f html -t pdf --template mhb_pandoc_template.latex > \
                static/$(basename $(dirname $fname)).pdf
          done
          tar czf pdfs.tar.gz static

      - name: Upload PDFs
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: pdfs.tar.gz
          retention-days: 2

  deploy-page:
    needs: [ gen-hugo ]
    runs-on: ubuntu-20.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2

      - name: Prepare page tree
        run: |
          tar xf page/page.tar.gz
          tar xf pdfs/pfds.tar.gz
          mv static public/pdfs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: endsWith(github.event.ref, '/master')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
